awdwd

diff --git a/.github/workflows/Fetch-API.yml b/.github/workflows/Fetch-API.yml
--- a/.github/workflows/Fetch-API.yml
+++ b/.github/workflows/Fetch-API.yml
@@ -18,7 +18,13 @@ jobs:
         mkdir -p data
         curl -o data/warStatus.json https://api.live.prod.thehelldiversgame.com/api/WarSeason/801/Status -H "Accept-Language: en-US,en;q=0.5"
         curl -o data/warInfo.json https://api.live.prod.thehelldiversgame.com/api/WarSeason/801/warinfo -H "Accept-Language: en-US,en;q=0.5"
-        curl -o data/warAPIStatus.json https://helldivers-2.fly.dev/api/801/status -H 'accept: application/json'         
+        curl -o data/warAPIStatus_.json https://helldivers-2.fly.dev/api/801/status -H 'accept: application/json'
+        if ! jq --exit-status '.errors.detail == "Not Found"' data/warAPIStatus_.json > /dev/null; then
+          mv data/warAPIStatus_.json data/warAPIStatus.json
+          echo "File renamed to warAPIStatus.json"
+        else
+          echo "Data matches the 'Not Found' object; file not renamed."
+        fi
     
     - name: Commit and Push if Changed
       run: |
